apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apigw.deploy" . }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "apigw.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "apigw.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
      - name: {{ include "apigw.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        env:
        - name: USERS_URL
          value: {{ include "users.url" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
