name: Api Gateway CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    name:  Analyzes source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Maven checkstyle
        run: mvn checkstyle:check
  tests:
    needs: [ checkstyle ]
    name: Run unitary, integration and CDCT tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Run unit tests
        run: mvn clean test -Punit
      - name: Run integration tests
        run: mvn clean test -Pit
      - name: Run CDCT tests
        run: mvn clean test -Pcdct
  publish-image:
    needs: [ tests ]
    name: Publish Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tfm-apigw
      IMAGE_TRUNK_TAG: trunk
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Create and publish docker image
        run: mvn jib:build -Dimage=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TRUNK_TAG }}

